---
title: "case_study"
author: "Siqing Wang"
date: "2023-10-10"
output: html_document
---

```{r}
library(p8105.datasets)
library(tidyverse)
library(ggridges)
library(leaflet)
data(nyc_airbnb)
```

```{r}
nyc_airbnb = nyc_airbnb |> 
  janitor::clean_names() |> 
  rename(borough = neighbourhood_group) |> 
  mutate(stars = review_scores_location/2)
```

## Brainstorm questions 
- Where are airbnbs expensive
  - borough? neighborhood?
  - do other factors affect price? what about rating?
- How long are airbnbs active?
  - illegal? shut down?
- which units have the most availabilities?
- how is review score impacted by location?
- how many apts are run by on host? 

## Exploring the data 
```{r}
nyc_airbnb |> count(borough)
```

```{r}
nyc_airbnb |> 
  group_by(borough, room_type) |> 
  summarize(mean_price = mean(price)) |> 
  pivot_wider(
    names_from = room_type,
    values_from = mean_price
  )
```

```{r}
nyc_airbnb |> 
  filter(price < 1000, room_type == "Entire home/apt") |> 
  ggplot(aes(x = price)) +
  geom_histogram() +
  facet_grid(. ~ borough)
```

```{r}
nyc_airbnb |> 
  filter(price < 1000, 
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  group_by(neighbourhood) |> 
  summarize(
    n_apt = n(),
    mean_price = mean(price)) |> 
  arrange(desc(mean_price))
```

```{r}
nyc_airbnb |> 
  filter(price < 1000, 
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) |> 
  ggplot(aes(x = price, y = neighbourhood)) +
  geom_density_ridges()
```

```{r}
nyc_airbnb |> 
  filter(price < 1000, 
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()
```

```{r}
nyc_airbnb |> 
  filter(price < 1000, 
         room_type == "Entire home/apt",
         borough == "Manhattan") |> 
  sample_n(500) |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addTiles() |> 
  addCircleMarkers(~lat, ~long, radius = .5)
```




